repos:
  - repo: local
    hooks:
      - id: openapi-bundle-and-lint
        name: OpenAPI Bundle and Lint
        entry: sh -c 'set -e; openapi bundle ./aws/api/v1/api-spec/main.yaml -o ./aws/api/v1/api-spec/bundled.yaml && openapi lint ./aws/api/v1/api-spec/bundled.yaml'
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.2
  #   hooks:
  #     - id: flake8

  # - repo: https://github.com/psf/black
  #   rev: 21.5b2
  #   hooks:
  #     - id: black
