name: Integration Tests

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aws-sam-cli
          pip install pytest

      - name: Build AWS SAM
        working-directory: ./aws
        run: |
          sam build

      - name: Run local API
        working-directory: .aws-sam/build/ApiV1Stack
        run: |
          sam local start-api &
          sleep 10

      - name: Run pytest
        run: pytest
